<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf915a61da65520300ef26125265c1740
{
    public static $prefixLengthsPsr4 = array (
        'Q' => 
        array (
            'QL\\Ext\\Lib\\' => 11,
            'QL\\Ext\\' => 7,
            'QL\\' => 3,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'QL\\Ext\\Lib\\' => 
        array (
            0 => __DIR__ . '/..' . '/jaeger/curlmulti',
            1 => __DIR__ . '/..' . '/jaeger/http',
        ),
        'QL\\Ext\\' => 
        array (
            0 => __DIR__ . '/..' . '/jaeger/querylist-ext-aquery',
            1 => __DIR__ . '/..' . '/jaeger/querylist-ext-multi',
            2 => __DIR__ . '/..' . '/jaeger/querylist-ext-request',
            3 => __DIR__ . '/..' . '/jaeger/querylist-ext-login',
            4 => __DIR__ . '/..' . '/jaeger/querylist-ext-dimage',
        ),
        'QL\\' => 
        array (
            0 => __DIR__ . '/..' . '/jaeger/querylist',
        ),
    );

    public static $classMap = array (
        'Callback' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'CallbackBody' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'CallbackParam' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'CallbackParameterToReference' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'CallbackReturnReference' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'CallbackReturnValue' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'DOMDocumentWrapper' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'DOMEvent' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'ICallbackNamed' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'phpQuery' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'phpQueryEvents' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'phpQueryObject' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
        'phpQueryPlugins' => __DIR__ . '/..' . '/jaeger/phpquery-single/phpQuery.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf915a61da65520300ef26125265c1740::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf915a61da65520300ef26125265c1740::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf915a61da65520300ef26125265c1740::$classMap;

        }, null, ClassLoader::class);
    }
}
