<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'QL\\Ext\\Lib\\' => array($vendorDir . '/jaeger/curlmulti', $vendorDir . '/jaeger/http'),
    'QL\\Ext\\' => array($vendorDir . '/jaeger/querylist-ext-aquery', $vendorDir . '/jaeger/querylist-ext-multi', $vendorDir . '/jaeger/querylist-ext-request', $vendorDir . '/jaeger/querylist-ext-login', $vendorDir . '/jaeger/querylist-ext-dimage'),
    'QL\\' => array($vendorDir . '/jaeger/querylist'),
);
